### PR TITLE
Snapshot Support

### PR DESCRIPTION
**Pull request by ahedengren**
Implemented snapshot support that passes test. Haven't tested in a production environment, yet. I suspect that will happen when I build modeling examples using the VMart database.

### CODE REVIEW

**Review by andyreagan — APPROVED** [review]
LGTM. This is a significant addition to the functionality!

**Comment by ahedengren** [comment]
Thanks @andyreagan ! 👍🏻

**Comment by andyreagan** [comment]
@ahedengren bump the version in setup.py, so we can deploy.

**Comment by andyreagan** [comment]
@ahedengren shoot, you're too fast!

maybe open another PR to bump the version, then you can push a local tag with the matching version (to automate the deploy).

**Pull request merged**
